language: php
php:
  - '7.1'
  - '7.2'

# Plan: check out a copy of Magento into another directory and symlink the repo into it.

script:
  - 'echo $TRAVIS_BUILD_DIR'
  - 'git clone --depth 1 --branch 2.3.2 https://github.com/magento/magento2.git /magento'
