matrix:
  include:
    -
      language: php
      php:
        - '7.2'
      env:
        - MAGENTO_VERSION="2.3.2" MAGENTO_PATH="/home/travis/magento"

      # Plan: check out a copy of Magento into another directory and symlink the repo into it.
      install:
        - 'echo $MAGENTO_PATH'
        - 'git clone --depth 1 --branch $MAGENTO_VERSION https://github.com/magento/magento2.git $MAGENTO_PATH'
        - 'cd $MAGENTO_PATH && composer install'
        # - '$MAGENTO_PATH/vendor/bin/phpcs --config-set installed_paths ../../magento/magento-coding-standard/'
        - 'mkdir -p $MAGENTO_PATH/app/code/Drip'
        - 'ln -s $TRAVIS_BUILD_DIR $MAGENTO_PATH/app/code/Drip/Connect'

      script:
        - 'cd $MAGENTO_PATH/dev/tests/unit && $MAGENTO_PATH/vendor/bin/phpunit $MAGENTO_PATH/app/code/Drip/Connect/Test/Unit'
        # - 'cd $MAGENTO_PATH && vendor/bin/phpcs --standard=Magento2 app/code/Drip/Connect'
    -
      language: node_js
      node_js:
        - '10'
      addons:
        chrome: stable
        hosts:
          - main.magento.localhost
          - site1.magento.localhost
        apt:
          packages:
            # Ubuntu 16+ does not install this dependency by default, so we need to install it ourselves
            - libgconf-2-4
      cache:
        # Caches $HOME/.npm when npm ci is default script command
        # Caches node_modules in all other cases
        npm: true
        directories:
          # we also need to cache folder with Cypress binary
          - ~/.cache
      install:
        - cd $TRAVIS_BUILD_DIR/devtools_m2/ && npm ci
      script:
        - cd $TRAVIS_BUILD_DIR/devtools_m2/ && ./tests.sh

