matrix:
  include:
    -
      language: php
      php:
        - '7.2'
      env:
        - MAGENTO_VERSION="2.3.5" MAGENTO_PATH="/home/travis/magento"

      # Plan: check out a copy of Magento into another directory and symlink the repo into it.
      install:
        - 'echo $MAGENTO_PATH'
        - 'git clone --depth 1 --branch $MAGENTO_VERSION https://github.com/magento/magento2.git $MAGENTO_PATH'
        - 'cd $MAGENTO_PATH && composer install'
        - '$MAGENTO_PATH/vendor/bin/phpcs --config-set installed_paths ../../magento/magento-coding-standard/'
        - 'mkdir -p $MAGENTO_PATH/app/code/Drip'
        - 'ln -s $TRAVIS_BUILD_DIR $MAGENTO_PATH/app/code/Drip/Connect'
        - 'ln -s $TRAVIS_BUILD_DIR/phpcs.xml $MAGENTO_PATH/phpcs.xml'

      script:
        - 'cd $MAGENTO_PATH && vendor/bin/phpcs app/code/Drip/Connect'
        - 'cd $MAGENTO_PATH/dev/tests/unit && $MAGENTO_PATH/vendor/bin/phpunit $MAGENTO_PATH/app/code/Drip/Connect/Test/Unit'
    #-
    #  language: node_js
    #  node_js:
    #    - '10'
    #  env:
    #    secure: KLIVg65GQEnm6/VN+EL3DRviLCJ1tHBuncMu6Hj5+2+mxLoTgB04fGkPIA/DrhTQIyua0Pfawj8BlAgCXjjzqdLiDhqLu1EYu2Dx/6WnqRh6Xyq1NphkYZPzOI7ogztSKbSl2POEGdjmLCOlbYl11SQUbUfbGvD+xhBGTI/S/WGJ/OnqRmAht7v+RXmWL2fUb5UwsbhcZ1dsHmpHaPF0HR68Jl9cPQyIvk8DpDjOl17M3Z8bGy6aNpW4qOgi99jxWAIM81Dsw5nAeaUuVSpvRSakE2y2/5vfyYuKhAlYt2KQrR8vODdbOydCwGbYQLLqNrBXW7hkuSZ1IZjtMBX8dRk2tNFsarVtVjM/DpH9KVEQasVtddLiVeD9TJ3FFtwz43VMdfQPagWWMahKVFWivh8pGGHQFM6VpJ8KalFdpCQbQtBsblxh9R+7pfzCHl3aG2iKj0L3i9yaYjcANKdSkqNjY2ZuroFq7NKNkWw+u/Y/9W734AJxnYR5iphRAy7vV/zfDck/irjqNoyKAn1QWR157lHk610KcAXBUJYruXHre5LdvqLDXhkgTZkXyNpaBiV9G0kemBvHfjDSwuHdvqBju1Qt7oFxxHjwVJz44zTMJjOnlcrHHoNogWG/NXoC1LNhRCQyicXllQUVvtWuRe0ZNjZp3gGESOZAbsxmkKU=
    #  addons:
    #    chrome: stable
    #    hosts:
    #      - main.magento.localhost
    #      - site1.magento.localhost
    #    apt:
    #      packages:
    #        # Ubuntu 16+ does not install this dependency by default, so we need to install it ourselves
    #        - libgconf-2-4
    #  cache:
    #    # Caches $HOME/.npm when npm ci is default script command
    #    # Caches node_modules in all other cases
    #    npm: true
    #    directories:
    #      # we also need to cache folder with Cypress binary
    #      - ~/.cache
    #  before_install:
    #    - pip install --user awscli
    #  install:
    #    - cd $TRAVIS_BUILD_DIR/devtools_m2/ && npm ci
    #  script:
    #    - cd $TRAVIS_BUILD_DIR/devtools_m2/ && ./tests.sh
