language: php
php:
  # - '7.1'
  - '7.2'
env:
  - MAGENTO_PATH="/home/travis/magento"

# Plan: check out a copy of Magento into another directory and symlink the repo into it.

script:
  - 'git clone --depth 1 --branch 2.3.2 https://github.com/magento/magento2.git $MAGENTO_PATH'
  - 'mkdir -p $MAGENTO_PATH/app/code/Drip'
  - 'ln -s $TRAVIS_BUILD_DIR $MAGENTO_PATH/app/code/Drip/Connect'
