language: php
php:
  - '7.0'
  - '7.2'
  - '7.3'

# Plan: check out a copy of Magento into another directory and symlink the repo into it.

script:
  - 'git clone --depth 1 --branch 2.3.2 https://github.com/magento/magento2.git /magento'
