version: '3.7'
services:
  web:
    build: .
    ports:
      - 3006:80
    links:
      - db
      - mock
      - opensearch
    environment:
      - MYSQL_DATABASE=magento
      - MYSQL_USER=magento
      - MYSQL_PASSWORD=magento
    volumes:
      - type: bind
        source: './..'
        target: /var/www/html/magento/app/code/Drip/Connect
        consistency: cached
      - type: bind
        source: './php_utils'
        target: /var/www/html/magento/app/code/Drip/TestUtils
        consistency: cached
  db:
    image: mariadb:10.4
    environment:
      - MARIADB_DATABASE=magento
      - MARIADB_USER=magento
      - MARIADB_PASSWORD=magento
      - MARIADB_RANDOM_ROOT_PASSWORD=true
    tmpfs: /var/lib/mysql
  opensearch:
    image: opensearchproject/opensearch:1.2.4
    environment:
      - discovery.type=single-node
      - DISABLE_SECURITY_PLUGIN=true
    tmpfs: /var/lib/mysql
  mock:
    image: mockserver/mockserver:mockserver-5.14.0
    ports:
    - 1080:1080
