version: '3.7'
services:
  web:
    image: 648846177135.dkr.ecr.us-east-1.amazonaws.com/eci/magento-m2-extension:2.3.5
    ports:
    - 3006:80
    links:
    - db
    environment:
      - MYSQL_DATABASE=magento
      - MYSQL_USER=magento
      - MYSQL_PASSWORD=magento
    volumes:
      - type: bind
        source: './..'
        target: /var/www/html/magento/app/code/Drip/Connect
        consistency: cached
  db:
    image: mysql:5.7.27
    environment:
      - MYSQL_DATABASE=magento
      - MYSQL_USER=magento
      - MYSQL_PASSWORD=magento
      - MYSQL_RANDOM_ROOT_PASSWORD=true
