version: '3.7'
services:
  web:
    links:
    - 'mock'
    volumes:
      - type: bind
        source: './php_utils'
        target: /var/www/html/magento/app/code/Drip/TestUtils
  db:
    tmpfs: /var/lib/mysql
  mock:
    image: jamesdbloom/mockserver:mockserver-5.7.0
    ports:
    - 1080:1080
