version: '3.7'
services:
  web:
    image: 648846177135.dkr.ecr.us-east-1.amazonaws.com/eci/magento-m2-extension:2.3.2
    # build: .
    ports:
      - 3006:80
    links:
      - db
      - mock
    environment:
      - MYSQL_DATABASE=magento
      - MYSQL_USER=magento
      - MYSQL_PASSWORD=magento
    volumes:
      - type: bind
        source: './..'
        target: /var/www/html/magento/app/code/Drip/Connect
        consistency: cached
      - type: bind
        source: './php_utils'
        target: /var/www/html/magento/app/code/Drip/TestUtils
        consistency: cached
  db:
    image: mysql:5.7.27
    environment:
      - MYSQL_DATABASE=magento
      - MYSQL_USER=magento
      - MYSQL_PASSWORD=magento
      - MYSQL_RANDOM_ROOT_PASSWORD=true
    tmpfs: /var/lib/mysql
  mock:
    image: jamesdbloom/mockserver:mockserver-5.7.0
    ports:
    - 1080:1080
