<?php if ($block->isModuleActive()) : ?>
    <?php $accountId = $block->getAccountParam(); ?>
    <?php if (!empty($accountId)) : ?>
        <!-- Drip -->
        <script type="text/javascript">
            var _dcq = _dcq || [];
            var _dcs = _dcs || {};
            _dcs.account = '<?=$accountId?>';

            (function() {
                var dc = document.createElement('script');
                dc.type = 'text/javascript'; dc.async = true;
                dc.src = '//tag.getdrip.com/<?=$accountId?>.js';
                var s = document.getElementsByTagName('script')[0];
                s.parentNode.insertBefore(dc, s);
            })();
        </script>
        <!-- Inject dynamically in order to bypass page caching... -->
        <script type="text/x-magento-init">
        {
            "*": {
                "Drip_Connect/js/identification": {}
            }
        }
        </script>
        <!-- end Drip -->
    <?php else : ?>
        <!-- Skipping Drip JS inclusion due to lack of account id -->
    <?php endif; ?>
<?php endif; ?>
