<?php if ($block->getConfig()->getValue('dripconnect_general/module_settings/is_enabled')) : ?>
    <?php $accountId = $block->getConfig()->getValue('dripconnect_general/api_settings/account_id'); ?>
    <!-- Drip -->
    <script type="text/javascript">
        var _dcq = _dcq || [];
        var _dcs = _dcs || {};
        _dcs.account = '<?=$accountId?>';

        (function() {
            var dc = document.createElement('script');
            dc.type = 'text/javascript'; dc.async = true;
            dc.src = '//tag.getdrip.com/<?=$accountId?>.js';
            var s = document.getElementsByTagName('script')[0];
            s.parentNode.insertBefore(dc, s);
        })();
    </script>
    <!-- end Drip -->
<?php endif; ?>
