<?php if ($block->isModuleActive()) : ?>
<?php
    $product = $block->getProduct();
    $currentPrice = $block->getHelper()->priceAsCents($product->getFinalPrice());
    $initialPrice = $block->getHelper()->priceAsCents($product->getPrice());
?>
    <!-- Drip track -->
    <script type="text/javascript">
    _dcq.push(["track", "Viewed a product", {
        product_id: "<?= $product->getId() ?>",
        sku: "<?= $product->getSku() ?>",
        name: "<?= $product->getName() ?>",
        brand: "<?= $block->getBrandName() ?>",
        categories: "<?= $block->getHelper()->getProductCategoryNames($product) ?>",
        price: "<?= $currentPrice ?>",
        <?php if ($currentPrice != $initialPrice) : ?>
        compared_at_price: "<?= $initialPrice ?>",
        <?php endif; ?>
        currency: "<?= $block->getStore()->getCurrentCurrencyCode() ?>",
        product_url: "<?= $product->getProductUrl() ?>",
        image_url: "<?= $block->getMediaUrl($product) ?>"
    }]);
    </script>
    <!-- end Drip track -->
<?php endif; ?>
