name: Drip Magento Plugin PHP Linting and Tests
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          path: 'plugin'
      - uses: actions/checkout@v3
        with:
          repository: 'magento/magento2'
          ref: ${{ matrix.magento }}
          path: 'magento'
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
      - run: 'cd magento/ && composer install'
      # We need the develop version of php-compatibility until https://github.com/PHPCompatibility/PHPCompatibility/issues/1312 is fixed.
      - run: 'cd magento/ && composer require phpcompatibility/php-compatibility' # We need to pull this in. Not sure how Magento does it.
      - run: 'magento/vendor/bin/phpcs --config-set installed_paths ../../magento/magento-coding-standard/'
      - run: 'mkdir -p magento/app/code/Drip'
      - run: 'ln -s $GITHUB_WORKSPACE/plugin/ $GITHUB_WORKSPACE/magento/app/code/Drip/Connect'
      - run: 'ln -s $GITHUB_WORKSPACE/plugin/phpcs.xml $GITHUB_WORKSPACE/magento/phpcs.xml'
      # Actual steps
      # TODO: Reduce and fix the warning severities.
      - run: 'cd magento/ && vendor/bin/phpcs --warning-severity=10 app/code/Drip/Connect'
      - run: 'cd magento/dev/tests/unit && magento/vendor/bin/phpunit magento/app/code/Drip/Connect/Test/Unit'
    strategy:
      matrix:
        php:
          # Generally run this on the oldest version we support and the newest. Feel free to add any that have special case breakage.
          - '7.4'
          # - '8.1'
        magento:
          - '2.4.4'
